import { getRandomNameAndAvatarUser } from '@api/user'
import { getDate } from '@utils/date'

import type { InboxModelType } from './message.type'

export const INBOX_LIST: InboxModelType[] = [
  {
    id: 'message-1',
    message: 'Hello Hamza miloud amar i Want you to make a website for me are you free',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ years: -1 }),
    type: 'starred',
    unread: true,
  },

  {
    id: 'message-2',
    message: 'nice to meet you i like your style of code',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ years: -2 }),
    type: 'starred',
    unread: false,
  },
  {
    id: 'message-3',
    message: 'Did you work with typescript or only javascript please I need your reply as fast as possible',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ years: -1.25 }),
    type: 'starred',
    unread: false,
  },
  {
    id: 'message-4',
    message: 'one of the best friend I ever seen thanks for the help',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ years: -1.15 }),
    type: 'starred',
    unread: false,
  },
  {
    id: 'message-5',
    message: 'Did you see the last RPG game I like it I think you gonna like it too',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -30 }),
    type: 'spam',
    unread: false,
  },
  {
    id: 'message-6',
    message: 'From here to there you never gonna find The biggest gift',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -45 }),
    type: 'spam',
    unread: false,
  },
  {
    id: 'message-7',
    message: 'can You play with me this game i like it',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -12 }),
    type: 'spam',
    unread: true,
  },
  {
    id: 'message-8',
    message: 'did you know the developer how develop this game',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -18 }),
    type: 'spam',
    unread: true,
  },
  {
    id: 'message-9',
    message: 'your frind is one the best player in call of ditty',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -1 }),
    type: 'spam',
    unread: true,
  },
  {
    id: 'message-10',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -1 }),
    type: 'spam',
    unread: true,
  },
  {
    id: 'message-11',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -0.15 }),
    type: 'spam',
    unread: false,
  },
  {
    id: 'message-12',
    message: 'your frind is one the best player in call of ditty',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -0.02 }),
    type: 'send',
    unread: false,
  },
  {
    id: 'message-13',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -0.2 }),
    type: 'send',
    unread: false,
  },
  {
    id: 'message-14',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -22 }),
    type: 'send',
    unread: false,
  },
  {
    id: 'message-15',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -19 }),
    type: 'send',
    unread: false,
  },
  {
    id: 'message-16',
    message: "Don't forget that every monday we play soccer please we are waiting for you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -18 }),
    type: 'send',
    unread: false,
  },
  {
    id: 'message-17',
    message: 'your frind is one the best player in call of ditty',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -17 }),
    type: 'send',
    unread: true,
  },
  {
    id: 'message-18',
    message:
      'Hello , And nice to meet you can you told me where i can find this gift you sand me because my friend girlfriend want it',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -2 }),
    type: 'send',
    unread: true,
  },
  {
    id: 'message-19',
    message: 'To play soccer in the summer one of the most difficult thing in the word',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -5 }),
    type: 'send',
    unread: true,
  },
  {
    id: 'message-20',
    message: 'Say Hello to someone every mooring make him happy all together to make the world huppy',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -32 }),
    type: 'draft',
    unread: true,
  },
  {
    id: 'message-21',
    message: 'Form here to there no one can know you better than me',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1 }),
    type: 'draft',
    unread: true,
  },
  {
    id: 'message-22',
    message: 'To play soccer in the summer one of the most difficult thing in the word',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -0.123 }),
    type: 'draft',
    unread: true,
  },
  {
    id: 'message-23',
    message: 'Did you sand message to Ketty Because she waiting for you',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -0.11 }),
    type: 'draft',
    unread: false,
  },
  {
    id: 'message-24',
    message: "Did you see the last horror movies I don't think that any body can watch it it too scary",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -0.1 }),
    type: 'draft',
    unread: false,
  },
  {
    id: 'message-25',
    message: 'I figure how i can fix my laptop thanks',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -22 }),
    type: 'draft',
    unread: false,
  },
  {
    id: 'message-26',
    message: "Did you see the last horror movies I don't think that any body can watch it it too scary",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -19 }),
    type: 'draft',
    unread: false,
  },
  {
    id: 'message-27',
    message:
      'Hello , And nice to meet you can you told me where i can find this gift you sand me because my friend girlfriend want it',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -22 }),
    type: 'draft',
    unread: false,
  },
  {
    id: 'message-28',
    message: 'Say Hello to someone every mooring make him happy all together to make the world huppy',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -14 }),
    type: 'draft',
    unread: true,
  },
  {
    id: 'message-29',
    message: "Don't forget that every monday we play soccer please we are waiting for you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -20 }),
    type: 'draft',
    unread: true,
  },
  {
    id: 'message-30',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1 }),
    type: 'trash',
    unread: true,
  },
  {
    id: 'message-31',
    message: 'Every morning i wake up I see you picture in front of my face are you insane',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -9 }),
    type: 'trash',
    unread: true,
  },
  {
    id: 'message-32',
    message: "Don't forget that every monday we play soccer please we are waiting for you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1.5 }),
    type: 'trash',
    unread: true,
  },
  {
    id: 'message-33',
    message: 'here we go and nice to meet you here are you sure you want this plat right now',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -20 }),
    type: 'trash',
    unread: true,
  },
  {
    id: 'message-34',
    message: 'Did You want to go to qatar to watch the final world cup',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1 }),
    type: 'trash',
    unread: true,
  },
  {
    id: 'message-35',
    message: 'No body can agree with what you say about css I think you are not good or you have something miss',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -9 }),
    type: 'trash',
    unread: true,
  },
  {
    id: 'message-36',
    message:
      "Did you find this blog in mdn or w3c because I look for it in long time and i don't see it can you please send me the link ",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1.5 }),
    type: 'trash',
    unread: true,
  },

  {
    id: 'message-37',
    message: "Don't forget that every monday we play soccer please we are waiting for you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -20 }),
    type: 'important',
    unread: false,
  },
  {
    id: 'message-38',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1 }),
    type: 'important',
    unread: false,
  },
  {
    id: 'message-39',
    message: 'Every morning i wake up I see you picture in front of my face are you insane',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -9 }),
    type: 'important',
    unread: false,
  },
  {
    id: 'message-40',
    message: "Don't forget that every monday we play soccer please we are waiting for you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1.5 }),
    type: 'important',
    unread: false,
  },
  {
    id: 'message-41',
    message: 'here we go and nice to meet you here are you sure you want this plat right now',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -20 }),
    type: 'important',
    unread: false,
  },
  {
    id: 'message-42',
    message: 'Did You want to go to qatar to watch the final world cup',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1 }),
    type: 'important',
    unread: false,
  },
  {
    id: 'message-43',
    message: 'No body can agree with what you say about css I think you are not good or you have something miss',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -9 }),
    type: 'important',
    unread: true,
  },
  {
    id: 'message-44',
    message:
      "Did you find this blog in mdn or w3c because I look for it in long time and i don't see it can you please send me the link ",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ month: -1.5 }),
    type: 'important',
    unread: true,
  },
  // Here we go
  {
    id: 'message-45',
    message: 'your frind is one the best player in call of ditty',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -1 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-46',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -1 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-47',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -0.15 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-48',
    message: 'your frind is one the best player in call of ditty',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -0.02 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-49',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ days: -0.2 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-50',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -22 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-51',
    message: "All the stuff you see here is for me don't take it with you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -19 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-52',
    message: "Don't forget that every monday we play soccer please we are waiting for you",
    user: getRandomNameAndAvatarUser(),
    date: getDate({ minutes: -18 }),
    type: 'snoozed',
    unread: true,
  },
  {
    id: 'message-53',
    message: 'your frind is one the best player in call of ditty',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -17 }),
    type: 'snoozed',
    unread: false,
  },
  {
    id: 'message-54',
    message:
      'Hello , And nice to meet you can you told me where i can find this gift you sand me because my friend girlfriend want it',
    user: getRandomNameAndAvatarUser(),
    date: getDate({ hours: -2 }),
    type: 'snoozed',
    unread: false,
  },
]
