export const FEEDBACK = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Web Developer',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 3,
    job: 'Web Designer',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 3,
    name: 'Bob Smith',
    email: 'bob@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 5,
    job: 'UX Designer',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 4,
    name: 'Alice Brown',
    email: 'alice@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Graphic Designer',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 5,
    name: 'John Doe',
    email: 'john@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Web Developer',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 6,
    name: 'Jane Doe',
    email: 'jane@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 3,
    job: 'Web Designer',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 7,
    name: 'Bob Smith',
    email: 'bob@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 5,
    job: 'UX Designer',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 8,
    name: 'Alice Brown',
    email: 'alice@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Graphic Designer',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 9,
    name: 'John Doe',
    email: 'john@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Web Developer',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 10,
    name: 'Jane Doe',
    email: 'jane@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 3,
    job: 'Web Designer',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 11,
    name: 'Bob Smith',
    email: 'bob@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 5,
    job: 'UX Designer',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 12,
    name: 'Alice Brown',
    email: 'alice@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Graphic Designer',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 13,
    name: 'John Doe',
    email: 'john@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 4,
    job: 'Web Developer',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 14,
    name: 'Jane Doe',
    email: 'jane@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 3,
    job: 'Web Designer',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 15,
    name: 'Bob Smith',
    email: 'bob@example.com',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.',
    rating: 5,
    job: 'UX Designer',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
]
