import { Building, Dollar, Users, Laptop, Movies, Video, Camera, Palette, Microphone } from '@pillar-ui/icons'
import { MetricCardProps } from './school.type'
import { Avatar } from '@pillar-ui/core'

const fakeData = (points: number, min: number, max: number) => {
  return Array.from({ length: points }, () => ({
    value: Math.floor(Math.random() * (max - min + 1)) + min,
  }))
}

export const METRICS: MetricCardProps[] = [
  {
    title: 'Total Students',
    value: 69325,
    change: 2.1,
    icon: <Users stroke="var(--Se9)" width="16" />,
    color: 'var(--Se9)',
    areaColor: 'var(--Se5)',
    data: fakeData(16, 50000, 150000),
  },
  {
    title: 'Total Teachers',
    value: 2658,
    change: -2.1,
    icon: <Users stroke="var(--Su9)" width="16" />,
    color: 'var(--Su9)',
    areaColor: 'var(--Su5)',
    data: fakeData(12, 2000, 3000),
  },
  {
    title: 'Total Staff',
    value: 3266,
    change: -2.1,
    icon: <Building stroke="var(--D9)" width="16" />,
    color: 'var(--D9)',
    areaColor: 'var(--D5)',
    data: fakeData(24, 1000, 3500),
  },
  {
    title: 'Total Revenue',
    value: 88357,
    change: 2.1,
    icon: <Dollar stroke="var(--I9)" width="16" />,
    color: 'var(--I9)',
    areaColor: 'var(--I5)',
    data: fakeData(12, 50000, 90000),
  },
]

export const ASSIGNMENT = [
  {
    category: 'User experience',
    description: 'Design',
    progress: 72,
    tasks: '120 Tasks',
  },
  {
    category: 'Basic fundamentals',
    description: 'Basic fundamentals',
    progress: 48,
    tasks: '32 Tasks',
  },
  {
    category: 'React native components',
    description: 'React native',
    progress: 15,
    tasks: '182 Tasks',
  },
  {
    category: 'Basic of music theory',
    description: 'Basic of music theory',
    progress: 24,
    tasks: '56 Tasks',
  },
]

export const COURSES = [
  {
    title: 'Videography Basic Design Course',
    views: '1.2k Views',
    course: <Avatar color="i" fallback={<Video width="24" />} corner="2" />,
  },
  {
    title: 'Basic Front-end Development Course',
    views: '834 Views',
    course: <Avatar color="i" fallback={<Laptop width="24" />} corner="2" />,
  },
  {
    title: 'Basic Fundamentals of Photography',
    views: '3.7k Views',
    isUpcomingWebinar: true,
    course: <Avatar color="su" fallback={<Camera width="24" />} corner="2" />,
  },
  {
    title: 'Advance Dribble Base Visual Design',
    views: '2.5k Views',
    course: <Avatar color="w" fallback={<Palette width="24" />} corner="2" />,
  },
  {
    title: 'Your First Singing Lesson',
    views: '948 Views',
    date: '17 Nov 23',
    duration: '32 minutes',
    joinEvent: true,
    course: <Avatar color="d" fallback={<Microphone width="24" />} corner="2" />,
  },
]

export const TEACHERS = [
  {
    course: 'UI/UX Design',
    teacher: 'Maybelle Zmitrovich',
    avatar: 'https://i.pravatar.cc/60?img=1',
    time: '19h 17m',
    progress: 100,
    bookCount: 14,
    studentCount: 48,
    chatCount: 43,
    type: 'Design',
  },
  {
    course: 'Typography Theory',
    teacher: 'Rollie Parsons',
    avatar: 'https://i.pravatar.cc/60?img=2',
    time: '16h 15m',
    progress: 11,
    bookCount: 209,
    studentCount: 20,
    chatCount: 98,
    type: 'Design',
  },
  {
    course: 'The Ultimate Drawing Course',
    teacher: 'Bernarr Markie',
    avatar: 'https://i.pravatar.cc/60?img=3',
    time: '16h 24m',
    progress: 12,
    bookCount: 116,
    studentCount: 33,
    chatCount: 53,
    type: 'Drawing',
  },
  {
    course: 'The Science of Everyday Thinking',
    teacher: 'Freda Garham',
    avatar: 'https://i.pravatar.cc/60?img=4',
    time: '8h 44m',
    progress: 81,
    bookCount: 79,
    studentCount: 46,
    chatCount: 27,
    type: 'Critical Thinking',
  },
  {
    course: 'The Science of Critical Thinking',
    teacher: 'Papageno Sloy',
    avatar: 'https://i.pravatar.cc/60?img=5',
    time: '4h 59m',
    progress: 11,
    bookCount: 274,
    studentCount: 21,
    chatCount: 160,
    type: 'Critical Thinking',
  },
  {
    course: 'Introduction to Mathematics',
    teacher: 'Eleanor Shellstrop',
    avatar: 'https://i.pravatar.cc/60?img=6',
    time: '12h 30m',
    progress: 60,
    bookCount: 150,
    studentCount: 35,
    chatCount: 75,
    type: 'Mathematics',
  },
  {
    course: 'Advanced Physics Concepts',
    teacher: 'Chidi Anagonye',
    avatar: 'https://i.pravatar.cc/60?img=7',
    time: '20h 05m',
    progress: 45,
    bookCount: 90,
    studentCount: 28,
    chatCount: 50,
    type: 'Physics',
  },
  {
    course: 'Organic Chemistry Essentials',
    teacher: 'Tahani Al-Jamil',
    avatar: 'https://i.pravatar.cc/60?img=8',
    time: '15h 45m',
    progress: 70,
    bookCount: 120,
    studentCount: 40,
    chatCount: 60,
    type: 'Chemistry',
  },
  {
    course: 'Fundamentals of Biology',
    teacher: 'Jason Mendoza',
    avatar: 'https://i.pravatar.cc/60?img=9',
    time: '10h 10m',
    progress: 100,
    bookCount: 200,
    studentCount: 55,
    chatCount: 90,
    type: 'Biology',
  },
  {
    course: 'World History from 1900',
    teacher: 'Janet',
    avatar: 'https://i.pravatar.cc/60?img=10',
    time: '18h 20m',
    progress: 30,
    bookCount: 180,
    studentCount: 42,
    chatCount: 80,
    type: 'History',
  },
  {
    course: 'American Literature Survey',
    teacher: 'Michael',
    avatar: 'https://i.pravatar.cc/60?img=11',
    time: '14h 50m',
    progress: 75,
    bookCount: 130,
    studentCount: 38,
    chatCount: 65,
    type: 'Literature',
  },
  {
    course: 'Data Structures and Algorithms',
    teacher: 'Shawn',
    avatar: 'https://i.pravatar.cc/60?img=12',
    time: '22h 15m',
    progress: 20,
    bookCount: 100,
    studentCount: 30,
    chatCount: 55,
    type: 'Computer Science',
  },
  {
    course: 'Renaissance Art History',
    teacher: 'Simone Garnett',
    avatar: 'https://i.pravatar.cc/60?img=13',
    time: '9h 00m',
    progress: 85,
    bookCount: 160,
    studentCount: 45,
    chatCount: 70,
    type: 'Art',
  },
  {
    course: 'Basic Music Theory Principles',
    teacher: 'Brent Norwalk',
    avatar: 'https://i.pravatar.cc/60?img=14',
    time: '7h 30m',
    progress: 50,
    bookCount: 110,
    studentCount: 32,
    chatCount: 62,
    type: 'Music',
  },
  {
    course: 'Physical Education Fundamentals',
    teacher: 'Gunnar Nyberg',
    avatar: 'https://i.pravatar.cc/60?img=15',
    time: '5h 20m',
    progress: 90,
    bookCount: 190,
    studentCount: 50,
    chatCount: 85,
    type: 'Physical',
  },
  {
    course: 'Principles of Economics',
    teacher: 'John Wheaton',
    avatar: 'https://i.pravatar.cc/60?img=16',
    time: '17h 40m',
    progress: 40,
    bookCount: 140,
    studentCount: 37,
    chatCount: 68,
    type: 'Economics',
  },
  {
    course: 'Introduction to Psychology',
    teacher: 'Alexei Luzhkov',
    avatar: 'https://i.pravatar.cc/60?img=17',
    time: '11h 05m',
    progress: 65,
    bookCount: 170,
    studentCount: 48,
    chatCount: 78,
    type: 'Psychology',
  },
  {
    course: 'Sociology: Core Concepts',
    teacher: 'Nikolaj Coster-Waldau',
    avatar: 'https://i.pravatar.cc/60?img=18',
    time: '13h 10m',
    progress: 35,
    bookCount: 125,
    studentCount: 35,
    chatCount: 65,
    type: 'Sociology',
  },
  {
    course: 'Political Science Essentials',
    teacher: 'Benedict Cumberbatch',
    avatar: 'https://i.pravatar.cc/60?img=19',
    time: '19h 55m',
    progress: 80,
    bookCount: 185,
    studentCount: 49,
    chatCount: 82,
    type: 'Political',
  },
  {
    course: 'Fundamentals of Philosophy',
    teacher: 'Idris Elba',
    avatar: 'https://i.pravatar.cc/60?img=20',
    time: '6h 45m',
    progress: 55,
    bookCount: 105,
    studentCount: 31,
    chatCount: 58,
    type: 'Philosophy',
  },
  {
    course: 'Exploring Astronomy Basics',
    teacher: 'Tom Hiddleston',
    avatar: 'https://i.pravatar.cc/60?img=21',
    time: '7h 10m',
    progress: 70,
    bookCount: 155,
    studentCount: 43,
    chatCount: 72,
    type: 'Astronomy',
  },
  {
    course: 'Introduction to Geography',
    teacher: 'Keanu Reeves',
    avatar: 'https://i.pravatar.cc/60?img=22',
    time: '9h 35m',
    progress: 25,
    bookCount: 115,
    studentCount: 34,
    chatCount: 63,
    type: 'Geography',
  },
  {
    course: 'Environmental Science Principles',
    teacher: 'Leonardo DiCaprio',
    avatar: 'https://i.pravatar.cc/60?img=23',
    time: '14h 00m',
    progress: 65,
    bookCount: 175,
    studentCount: 47,
    chatCount: 77,
    type: 'Environmental Science',
  },
  {
    course: 'Creative Writing Workshop',
    teacher: 'Meryl Streep',
    avatar: 'https://i.pravatar.cc/60?img=24',
    time: '10h 25m',
    progress: 40,
    bookCount: 135,
    studentCount: 39,
    chatCount: 69,
    type: 'Creative Writing',
  },
  {
    course: 'Drama and Theatrical Arts',
    teacher: 'Cate Blanchett',
    avatar: 'https://i.pravatar.cc/60?img=25',
    time: '11h 50m',
    progress: 75,
    bookCount: 165,
    studentCount: 46,
    chatCount: 74,
    type: 'Drama',
  },
]

export const EARNING_MONTH = [
  { month: 'Jan', earnings: 40000, expanse: 28000 },
  { month: 'Feb', earnings: 30000, expanse: 22000 },
  { month: 'Mar', earnings: 35000, expanse: 30000 },
  { month: 'Apr', earnings: 42000, expanse: 25000 },
  { month: 'May', earnings: 38000, expanse: 29000 },
  { month: 'Jun', earnings: 25000, expanse: 18000 },
  { month: 'Jul', earnings: 32000, expanse: 24000 },
  { month: 'Aug', earnings: 45000, expanse: 32000 },
  { month: 'Sep', earnings: 39000, expanse: 31000 },
  { month: 'Oct', earnings: 37000, expanse: 27000 },
  { month: 'Nov', earnings: 41000, expanse: 30000 },
  { month: 'Dec', earnings: 48000, expanse: 35000 },
]
